//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalServicesAirlines
{
    using System;
    using System.Collections.Generic;
    
    public partial class airline
    {
        public airline()
        {
            this.pilots = new HashSet<pilots>();
        }
    
        public int id_airline { get; set; }
        public string descripcion { get; set; }
        public string ciudad { get; set; }
        public int numero_aviones { get; set; }
        public string rutas { get; set; }
    
        public virtual ICollection<pilots> pilots { get; set; }
    }
}
